auto: true

name: amaGama
description: Web service for implementing a large-scale translation memory.
latest_version: 0.0
author: Translate House

about_url: http://translatehouse.org/about.html
docs_url: http://docs.translatehouse.org/projects/amagama/
gh_url: https://github.com/translate/amagama
